egresso/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :students
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

egresso/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

egresso/app/models/course.rb
class Course < ApplicationRecord
end

egresso/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
end

egresso/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

egresso/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:nome, :sigla, :site, :coordenador, :matricula, :senha)
    end
end

egresso/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

egresso/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @cursos = Course.all
  end

  # GET /students/1/edit
  def edit
    @cursos = Course.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:nome, :matricula, :email, :telefone, :ano, :semestre, :senha, :course_id)
    end
end

egresso/app/helpers/application_helper.rb
module ApplicationHelper
end

egresso/app/helpers/courses_helper.rb
module CoursesHelper
end

egresso/app/helpers/home_helper.rb
module HomeHelper
end

egresso/app/helpers/students_helper.rb
module StudentsHelper
end

egresso/app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">

  <div class="form-group col-lg-4">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :course_nome, class:'form-control' %>
  </div>

<div class="form-group col-lg-1">
    <%= form.label :sigla %>
    <%= form.text_field :sigla, id: :course_sigla, class:'form-control' %>
  </div>

  <div class="form-group col-lg-4">
    <%= form.label :site %>
    <%= form.text_field :site, id: :course_site, class:'form-control' %>
  </div>

  <div class="form-group col-lg-4">
    <%= form.label :coordenador %>
    <%= form.text_field :coordenador, id: :course_coordenador, class:'form-control' %>
  </div>

  <div class="form-group col-lg-2">
    <%= form.label :matricula %>
    <%= form.text_field :matricula, id: :course_matricula, class:'form-control' %>
  </div>

  <div class="form-group col-lg-2">
    <%= form.label :senha %>
    <%= form.text_field :senha, id: :course_senha, class:'form-control' %>
  </div>

</div>


  <button type="button" class="btn btn-success">
    <%= form.submit %>
  </button>
<% end %>

egresso/app/views/courses/edit.html.erb
<h1>Atualizar Informações de Curso</h1>

<%= render 'form', course: @course %>

<br>

<%= link_to 'Voltar', courses_path %>

egresso/app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cursos - IFPB</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sigla</th>
      <th>Site</th>
      <th>Coordenador</th>
      <th>Matricula</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.nome %></td>
        <td><%= course.sigla %></td>
        <td><%= course.site %></td>
        <td><%= course.coordenador %></td>
        <td><%= course.matricula %></td>
        <td><%= course.senha %></td>
        <td><%= link_to 'Mais Informações', course %></td>
        <td><%= link_to 'Editar Curso', edit_course_path(course) %></td>
        <td><%= link_to 'Apagar Curso', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Curso', new_course_path %>

egresso/app/views/courses/new.html.erb
<h1>Cadastro de Curso</h1>

<%= render 'form', course: @course %>

<br>
<%= link_to 'Voltar', courses_path %>

egresso/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="list-group">

</div>

<p>
  <strong>Nome:</strong>
  <%= @course.nome %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @course.sigla %>
</p>

<p>
  <strong>Site:</strong>
  <%= @course.site %>
</p>

<p>
  <strong>Coordenador:</strong>
  <%= @course.coordenador %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @course.matricula %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @course.senha %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

egresso/app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Home - Index</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-success" href="#" role="button">Learn more</a>
</div>

egresso/app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <a class="navbar-brand" href="<%= root_path %>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%= courses_path %>">Cursos <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%= students_path %>">Estudantes</a>
    </div>
  </div>
</nav>

egresso/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Egresso</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "/layouts/menu" %>
    <%= yield %>
  </body>
</html>

egresso/app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :student_nome %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.text_field :matricula, id: :student_matricula %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :student_email %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :student_telefone %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano, id: :student_ano %>
  </div>

  <div class="field">
    <%= form.label :semestre %>
    <%= form.number_field :semestre, id: :student_semestre %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha, id: :student_senha %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= collection_select(:student, :course_id, @cursos, :id, :nome) %>>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

egresso/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

egresso/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudantes - IFPB</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Ano</th>
      <th>Semestre</th>
      <th>Senha</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.nome %></td>
        <td><%= student.matricula %></td>
        <td><%= student.email %></td>
        <td><%= student.telefone %></td>
        <td><%= student.ano %></td>
        <td><%= student.semestre %></td>
        <td><%= student.senha %></td>
        <td><%= student.course %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastro de Estudante', new_student_path %>

egresso/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

egresso/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @student.nome %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @student.matricula %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @student.telefone %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @student.ano %>
</p>

<p>
  <strong>Semestre:</strong>
  <%= @student.semestre %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @student.senha %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>